# Generated by Django 2.0.3 on 2018-04-22 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goodday', '0002_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
